### ISSUE TITLE
Problem whit connect with google account 

### ISSUE THREAD

**Issue by ViajesIkea** [krayin/krayin-google-integration#43]
# Title
Problem whit connect with google account 

# Issue
I have a problem whit google account of krayin-google-integration. When I try connect with google, I have many problems. I show you the screenshots.

# Actual result

![googleAccountClient](https://user-images.githubusercontent.com/36205153/172825374-16f55967-4722-42b8-a913-71904542f80f.PNG)

![googleAccount](https://user-images.githubusercontent.com/36205153/172825377-d6cc0e5a-a8d7-4b89-ad2e-7475a6b821a4.PNG)

**Comment by ViajesIkea** [comment]
Yes, I did, but I keep getting the error:

Error 400: invalid_request
Missing required parameter: scope

**Comment by Sanjaybhattwebkul** [comment]
@ViajesIkea 

I **guess** you haven't **configured** your account properly on **google console cloud.**
Please **complete** the **all** required **steps**, then try **again**

**Comment by Sanjaybhattwebkul** [comment]
You need to **add** _Authorized redirect URIs_, _User_  and some other fields

**Comment by Sanjaybhattwebkul** [comment]
> Hi @ViajesIkea
> 
> Please add the user to **google console cloud** and the issue **will be resolved.** Please take a **reference** from [Here](https://prnt.sc/IKB_mB8ldstX)

Add the email address to **google console cloud** from which you want to fetch the calendar

**Comment by Sanjaybhattwebkul** [comment]
Closing this issue as **not getting any response from the last 3 months.**

Feel free to **reopen** if you have any queries.
